### ISSUE TITLE
Report suggests jQuery plugin not installed

### ISSUE THREAD

**Issue by sirkitree** [backdrop-contrib/nivo_slider#1]
Taking a look at my `admin/reports/status` I'm seeing the following:
![status report beta vrsites com 2015-01-23 09-00-46](https://cloud.githubusercontent.com/assets/28543/5877677/7eac47f8-a2de-11e4-945c-bd503fbeb6f5.png)

Nivo slider is working however, so I'm wondering if this is a remnant of the Drupal module which uses library module and jQuery update?

**Comment by docwilmot** [comment]
Oops, left in hook_requirements(), because I didn't realize that that hook was responsible for status messages; now I know!

**Comment by docwilmot** [comment]
Fixed.
