### ISSUE TITLE
How do I upgrade?

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/nivo_slider#2]
Thanks for an excellent module to have ported to Backdrop.
I see that your new release says 'Upgrade path has been removed as it is impossible.'

I have a working earlier version of this module but I get the erroneous status report reported in issue 1. I have tried loading the new release 2.0.0 but got this
![nivosliderreport2](https://cloud.githubusercontent.com/assets/10559274/9974584/96f502e8-5e8e-11e5-945c-19993b4a2989.png)
So I have hastily reverted to the previous version. Any advice please?

**Comment by docwilmot** [comment]
Hi @Graham-72, I think I was a bit lazy about this. An upgrade process wasnt that hard at all.
See new 2.x please. Just replace your 1.x with the up to date 2.x and run updates. Would be grateful if you could let me know how it goes.

**Comment by docwilmot** [comment]
Edit, dont yet. It works for upgrade, but if you go back and configure your slide, it deletes them. This might be a pre-existing 2.0 problem, as I can see why the upgrade process would do that. Back to work then.

**Comment by docwilmot** [comment]
yep pre-exisitn 2.0 issue. How I missed that??

**Comment by Graham-72** [comment]
Thanks.

It is getting late here. I will try tomorrow and report back.

**Comment by docwilmot** [comment]
Ok couple of fixes. If you could test for me please will push new release

**Comment by Graham-72** [comment]
I have now successfully upgraded my site, thank you.
Just one thing puzzles me, your repo does not include a default config file. I have kept my old one but perhaps this is unnecessary?

**Comment by docwilmot** [comment]
thanks. glad it went well.
no config this version, saving defaults in an array;

**Comment by docwilmot** [comment]
Fixed, AFAICT.
