### ISSUE TITLE
Undefined index nivo_slider_image_style

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/nivo_slider#4]
I am getting this error report:
Notice: Undefined index: nivo_slider_image_style in nivo_slider_slide_configuration_form() (line 76 of /var/www/vhosts/browsersbookshops.com/httpdocs/backdrop/modules/nivo_slider/nivo_slider_slides.admin.inc).
There is a similar problem in line 85 with nivo_slider_image_style_slide.
It seems the indexes should just be 'image_style' and 'image_style_slide' and I will try and create the PR for you.

**Comment by docwilmot** [comment]
This is fixed
