### ISSUE TITLE
error in nivo slider documentation for backdrop cms - folder nivo_slider needs to be nivo-slider

### ISSUE THREAD

**Issue by jsfry** [backdrop-contrib/nivo_slider#6]
HI , Firstly, love backdrop - much lighter and quicker than drupal.  But been
pulling my hair out for a 1/2 hour trying to get nivo slider to work in Backdrop cms 
and finally realized that your documentation on
the backdrop site for nivo slider is wrong.  The name of the folder for nivo
slider in the "libraries" folder in the backdrop site root should be renamed to nivo-slider not
nivo_slider (as your documentation on the module page suggests).  This was giving me : "Warning : undefined index in line 76 of *.inc file in the module folder).

Pls correct for others.  I tried to contact docwilmot
(maintainer) via github but couldn't find a contact form over there so am
doing it here.   The documentation which I read which has the error is here:
https://backdropcms.org/project/nivo_slider    (see under "Installation"
first bullet point).

best,
Jeff

**Comment by Graham-72** [comment]
Yes, and I think there may be one or two other issues. I got nivo-slider working on a site several months ago, and it still works, but there have been changes and I cannot get it to work on a new installation.

**Comment by jsfry** [comment]
just got it to work on my backdrop site in case you want to ask questions.
Jeff

**Comment by Graham-72** [comment]
That's good news, well done. I will have another go in a week or so, and maybe have some questions then. Di you have a look at the other issues here?

**Comment by serundeputy** [comment]
README.md `PR`: https://github.com/backdrop-contrib/nivo_slider/pull/7

**Comment by jsfry** [comment]
I'll check out those other issues when I have a chance and see if I have 
any insight .

Best,
Jeff

**Comment by Graham-72** [comment]
@jsfry are you getting nivo slider appearing in your admin menu? I have got as far as creating a block and adding 3 images, but cannot get to edit this block unless I enter the URL ..../admin/structure/nivo-slider/ which then reveals a listing of slider blocks showing the one I have added.

**Comment by klonos** [comment]
I'm gonna go ahead and close this old issue as outdated/irrelevant. The nivo slider library is now bundled with the module - there is no need for people to manually download it - just enable the module and you should be ready to go 😉
