### ISSUE TITLE
Request to be a (co-)maintainer.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/nivo_slider#8]
Hey @docwilmot 👋🏼 

Not sure if you are still looking after this module, but I would like to offer to help maintain it.

We seem to be behind a few commits compared to the 7.x branch (see https://git.drupalcode.org/project/nivo_slider/-/commits/7.x-1.x), and one of these commits specifically adds the ability to configure sides links to open in a new window (see https://git.drupalcode.org/project/nivo_slider/-/commit/6a5464b9ee8b24bfa4263a5e3ea058439c059471), which is a feature that someone coming from D7 has already requested in Zulip.

In general though, I'd be glad to help maintain this module.

Thanks in advance for considering,
Cheers

**Comment by docwilmot** [comment]
No problem, send the PR please.

**Comment by klonos** [comment]
Done @docwilmot: https://github.com/backdrop-contrib/nivo_slider/pull/9

**Comment by klonos** [comment]
Thanks @docwilmot 👍🏼
